# Site settings
title: Hugo Calderón Blog
description: This is only other blog of a Enthusiastic programmer
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://hugocalderon.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hugo Calderón
user_title: Web Developer
email: albert.hugo@hotmail.com
instagram_username: lhugo_alberto
facebook_username: lhugoalberto
github_username:  hugocalderon
linkedin_username : lhugoalberto

# Google-analytics
google-analytics:
  id: "UA-98210758-2"

exclude: ['package.json', 'src' , 'node_modules']
